### ISSUE TITLE
Javascript error while using Star-Rating plugin

### ISSUE THREAD

**Issue by alorszut** [codeshell/grav-plugin-comments#1]
Hi Codeshell,

I installed the star-rating plugin on my grav blog : https://github.com/getgrav/grav-plugin-star-ratings
I also added your modified comments plugin into the blog, but now I can no more change the star ratings when clicking on the stars.

As I'm not a javascript expert, have you got some time to check this issue.
When reverting to the original comments plugins, everything works well.

TX in advance.

**Comment by codeshell** [comment]
Tested with Star Ratings v2.0.1 using
```twig
        {% if config.plugins['star-ratings'].enabled %}
            {{ stars(page.route) }}
        {% endif %}
```
in my own template. Rating worked. Changing the rating was only possible when disabling the unique IP check. Otherwise the vote is irreversible.

That's how the star-ratings plugin seems to work.
```php
// https://github.com/getgrav/grav-plugin-star-ratings/blob/develop/star-ratings.php
        if ($this->config->get('plugins.star-ratings.unique_ip_check')) {
            if (!$this->validateIp($id)) {
                $voted = true;
            }
        }
```
```js
// https://github.com/getgrav/grav-plugin-star-ratings/blob/develop/assets/star-ratings.js
            if (element.data('voted')) {
                options.readOnly = true;
            }
```
